### ISSUE TITLE
Error when building with webpack

### ISSUE THREAD

**Issue by Alex-Sokolov** [vue-generators/vue-form-generator#375]
![image](https://user-images.githubusercontent.com/4497128/34936462-8a355416-f9f2-11e7-8a9d-9bb486534376.png)

Importing:
```js
import VueFormGenerator from 'vue-form-generator';
import 'vue-form-generator/dist/vfg.css';
```

Inside `vue-form-generator/dist/vfg.css` at the end 
```css
.vue-form-generator .field-switch input:checked~.handle{
    left:91px;
    left:calc(100% - ($field-switch-height - 1px));
    box-shadow:-1px 1px 5px rgba(0,0,0,.2)
}
```

If switch to `import 'vue-form-generator/dist/vfg-core.css';` all works
